version: '3'

networks:
  vpn:
    driver: bridge

services:
  prometheus-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - '3000:3000'
#    user: 'cyasam7'
#    volume: '$PWD/data:/var/lib/grafana'
